deprecate ownerAlias
OpsLevel/cli pull request #191
Opened 2023-10-20 17:46 UTC by taimoor-at-opslevel

## Issues

https://github.com/OpsLevel/opslevel-go/issues/276

## Changelog

- [x] Update help for using owner as an identifier input
- [x] Make a `changie` entry

## Tophatting

```
$ cat service.yml
name: "some new service from CLI"
description: "some new service created on CLI"
product: "whatever"
language: "ruby"
tier: "tier_2"
framework: "rails"
owner:
  alias: "platform"%
$ opslevel create service -f service.yml
"Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS84MjA1OQ"

$ cat service_update.yml
id: "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS84MjA1OQ"
description: "some new service created on CLI - now updated"
owner:
  id: "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xMTEwOA"%
$ opslevel update service -f service_update.yml
# success, truncating JSON output.
```

2023-10-20 17:53 UTC, rocktavious requested changes
can you investigate the `opslevel export terraform` command code and see if there needs to be changes there too?

2023-10-23 17:41 UTC, taimoor-at-opslevel commented
> can you investigate the `opslevel export terraform` command code and see if there needs to be changes there too?

Looks good to me!

```
resource "opslevel_service" "some_new_service_from_cli" {
  name = "some new service from CLI"
  description = "some new service created on CLI - now updated"
  product = "whatever"
  framework = "rails"
  language = "ruby"
  
  tier_alias = data.opslevel_tier.tier_2.alias
  owner_alias = opslevel_team.platform_2.alias

  aliases = ["some_new_service_from_cli"]
  
}

```

2023-10-23 18:29 UTC, rocktavious commented
> > can you investigate the `opslevel export terraform` command code and see if there needs to be changes there too?
> 
> Looks good to me!
> 
> ```
> resource "opslevel_service" "some_new_service_from_cli" {
>   name = "some new service from CLI"
>   description = "some new service created on CLI - now updated"
>   product = "whatever"
>   framework = "rails"
>   language = "ruby"
>   
>   tier_alias = data.opslevel_tier.tier_2.alias
>   owner_alias = opslevel_team.platform_2.alias
> 
>   aliases = ["some_new_service_from_cli"]
>   
> }
> ```

Well that depends on if you have to change the terraform to support ID or Alias now.

2023-10-23 19:14 UTC, rocktavious commented on src/cmd/service.go
>  			if tier != "" {
```suggestion
			if owner != "" {
```

2023-10-23 19:14 UTC, rocktavious commented on src/cmd/service.go
>  			if tier != "" {
Also line 211 is wrong - looks like bad code from before

2023-10-23 19:15 UTC, rocktavious approved these changes
other then 1 suggestion it seems good

2023-10-24 13:48 UTC, davidbloss approved these changes
LGTM 🎉

2023-10-25 17:44 UTC, merged